### ISSUE TITLE
Error when running ceda-cc

### ISSUE THREAD

**Issue by mollymacrae** [cedadev/ceda-cc#34]
Hi, I have copied across the latest ceda-cc version with RAMIP but I am getting this error when running it on any files (including other projects to ramip):

Traceback (most recent call last):
  File "/datacentre/processing3/RAMIP/ramip-venv/bin/ceda-cc", line 8, in <module>
    sys.exit(main_entry())
  File "/datacentre/processing3/RAMIP/ramip-venv/lib/python3.8/site-packages/ceda_cc/c4.py", line 34, in main_entry
    m.run(printInfo=True)
  File "/datacentre/processing3/RAMIP/ramip-venv/lib/python3.8/site-packages/ceda_cc/c4_run.py", line 341, in run
    self.cc.checkfile( f, log=flogger,attributeMappings=self.c4i.attributeMappings, getDrs=self.c4i.getDrs )
  File "/datacentre/processing3/RAMIP/ramip-venv/lib/python3.8/site-packages/ceda_cc/c4_run.py", line 231, in checkfile
    vgroup = self.info.pcfg.mipvocabvgmap.get(self.cfn.group,self.cfn.group)
AttributeError: 'ProjectConfig' object has no attribute 'mipvocabvgmap'

**Comment by mollymacrae** [comment]
I think 'mipvocabvgmap' needs to be changed back to 'mipVocabVgmap' in line 231 of c4_run.py
